try {
}
catch (error) {
}
function getError(error) {
    if (error instanceof Error) {
        console.log(error.message);
    }
}
export const test = '';
